### ISSUE TITLE
Created a compatible version of this app.

### ISSUE THREAD

**Issue by sainath13** [VctrySam/Twitter#2]
Hi, if you are facing issues in getting this app up and running, refer to this link 
[https://github.com/sainath13/Twitter](url)
I have created a compatible version that will directly run on your machine.
I wanted to submit a pull request but not sure how it will work.

**Comment by reganjelcic** [comment]
SAM OKORO IS A SCAMMER!!!! READ ABOUT HIM HERE http://www.vctrysam.com/

**Comment by reganjelcic** [comment]
SAM OKORO IS A SCAMMER!!!! READ ABOUT HIM HERE http://www.vctrysam.com/
